apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: ghcr.io/loresuso/busybox:latest
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always