apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox
spec:
  selector:
    matchLabels:
      name: busybox
  template:
    metadata:
      labels:
        name: busybox
    spec:
      containers:
        - image: ghcr.io/loresuso/busybox:latest
          imagePullPolicy: Always
          name: busybox
      terminationGracePeriodSeconds: 30